name: Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 'node' ] 

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install Dependencies
      run: yarn

    - name: Run Jest Tests
      run: yarn test

    - name: Move coverage badge
      run: |
        mkdir -p .github/badges
        cp coverage/badge-lines.svg .github/badges/coverage.svg

    - name: Commit and Push Badge to badges branch
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git fetch origin badges || true
        git switch -C badges origin/badges || git switch -c badges
        cp .github/badges/coverage.svg coverage.svg
        git add coverage.svg
        git commit -m "Update coverage badge" || echo "No changes to commit"
        git push origin badges
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
